name: Check and deploy to Prod

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - main
    types: [ closed ]


jobs:
  secrets_rotator:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -lrt
          git status
          echo " TODO more here"
